### ISSUE TITLE
Tv shows

### ISSUE THREAD

**Issue by tvstreamscript** [pixelead0/tmdb_v3-PHP-API-#11]
this class is only for movies ?
i need also for tvshows

**Comment by Alvaroctal** [comment]
I was looking for the same, so I forked the project, changed a bit the usage and now supports (easily) TVShow, is still under development and I'm planing to add some things, but TV Shows seems to work fine.
[https://github.com/Alvaroctal/TMDB-PHP-API](https://github.com/Alvaroctal/TMDB-PHP-API)
