### ISSUE TITLE
Unable to read configuration, verify that the API key is valid

### ISSUE THREAD

**Issue by gc-017** [pixelead0/tmdb_v3-PHP-API-#19]
API is vaild, but i dont know why i get this error "Unable to read configuration, verify that the API key is valid" but only on free hosting. Local host works normaly (I am creating site only for my personal use).
When i modified line checking api key i got error that say its invaild argument for foreach, but when i clicked on check request its everything there.

Dont know what more to say...
http://www.hostinger.com/ <---- free host

**Comment by Alvaroctal** [comment]
Doesn't seems to be a wrapper related issue. Maybe you should try posting in the [TMDB Forum](https://www.themoviedb.org/talk) in the API support.
But probably, hostinger servers are banned from the API.

tip: don't use hostinger in general, is shit.

**Comment by gc-017** [comment]
Ok, thanks. Would you recommend me some free servers that i can try? Because as i previously said, at this moment this is only for me and in the future it will be extended to max 3-4 people, so paid hosts are waste for this.
