### ISSUE TITLE
How can I get imdb id of show?

### ISSUE THREAD

**Issue by ibrahimmumcu** [pixelead0/tmdb_v3-PHP-API-#25]
<?php
$idTVShow = $_GET['id'];
$tvShow = $tmdb->getTVShow($idTVShow);
print_r($tvShow);
?>

This code doesn't return any imdb id. How can I get it?

**Comment by apprecht** [comment]
As I know there is now way to get the IMDB-ID you can only search by it, but it wont be part of the output of this API

**Comment by ibrahimmumcu** [comment]
Ops! That's sad :(
