### ISSUE TITLE
Es posible buscar una pelicula con el nombre y el año?

### ISSUE THREAD

**Issue by joseska** [pixelead0/tmdb_v3-PHP-API-#32]
Es posible buscar una pelicula por el nombre y el año?

Gracias....

**Comment by Alvaroctal** [comment]
De acuerdo con la [api](http://docs.themoviedb.apiary.io/#reference/search/searchmovie), si es posible. Pero habría que añadírselo a la librería.

un saludo

**Comment by pixelead0** [comment]
En:
```
public function searchMovie($movieTitle){
		$movies = array();
		$result = $this->_call('search/movie', 'query='. urlencode($movieTitle), $this->getLang());
		...

```

Intenta agregando &year en $result:

`$result = $this->_call('search/movie', 'query='. urlencode($movieTitle) . '&year=2009', $this->getLang());
`

Tendrías que crear una funcion similar a getLa

**Comment by joseska** [comment]
Gracias, me sirvió de mucho. al final quedo así:
public function searchMovie2($movieTitle, $movieYear){

		$movies = array();

		// $result = $this->_call('search/movie', 'query='. urlencode($movieTitle), $this->getLang());
        //modificado SKA
        $result = $this->_call('search/movie', 'query='. urlencode($movieTitle) . '&year='.urlencode($movieYear), $this->getLang());

		foreach($result['results'] as $data){
			$movies[] = new Movie($data);
		}

		return $movies;
	}
