### ISSUE TITLE
trailers are always empty

### ISSUE THREAD

**Issue by kirkdm** [pixelead0/tmdb_v3-PHP-API-#41]
throws error Undefined index: trailers when calling movie->getTrailers()

**Comment by Alvaroctal** [comment]
hi, 

Maybe you are [iterating](https://github.com/pixelead0/tmdb_v3-PHP-API-/blob/master/examples/movies/findMovie.php) over a search? Keep in mind that trailers attribute is only loaded when you [get](https://github.com/pixelead0/tmdb_v3-PHP-API-/blob/master/examples/movies/infoMovie.php#L11)  a Movie by its ID.
