### ISSUE TITLE
Warning: Illegal string

### ISSUE THREAD

**Issue by slaymantis** [pixelead0/tmdb_v3-PHP-API-#44]
Hi I seem to get these errors when running the example files

Warning: Illegal string offset 'apikey' in /www/sites/tmdb/wwwroot/controller/classes/config/Configuration.php on line 42

Warning: Illegal string offset 'lang' in /www/sites/tmdb/wwwroot/controller/classes/config/Configuration.php on line 43

Warning: Illegal string offset 'adult' in /www/sites/tmdb/wwwroot/controller/classes/config/Configuration.php on line 45

Warning: Illegal string offset 'debug' in /www/sites/tmdb/wwwroot/controller/classes/config/Configuration.php on line 46

Warning: Illegal string offset 'appender' in /www/sites/tmdb/wwwroot/controller/classes/config/Configuration.php on line 48

Warning: Invalid argument supplied for foreach() in /www/sites/tmdb/wwwroot/controller/classes/config/Configuration.php on line 48

**Comment by bogdanfinn** [comment]
In the ./examples/index.php file try to change the following line:

` $tmdb = new TMDB($apikey, 'en', true);`
to 
` $tmdb = new TMDB();`

make sure to add you api key under ./configuration/default.php

The TMDB Class expects an array as constructor parameter. In the example file the Class is instantiated with 3 parameters for the constructor. If you pass no config-array as a parameter the class should load the default configuration in the ./configuration directory.

Hope this helps you :)
