### ISSUE TITLE
Get Release Dates

### ISSUE THREAD

**Issue by yordanoff** [pixelead0/tmdb_v3-PHP-API-#46]
Hello! Is it possible to get the release dates for different countries like in this [example](https://developers.themoviedb.org/3/movies/get-movie-release-dates)?

**Comment by bogdanfinn** [comment]
Without modification you should be able to get the releasedates by modifiying your configuration and append ''
`$cnf['appender']['movie'] = array('trailers', 'images', 'credits', 'translations', 'reviews', 'release_dates');`

After that you can access the data array by the get Method for a detailed movie object:
`$movie->get('release_dates')['results'];`

I can add functionality to access the releasedates in another PR later.
