### ISSUE TITLE
Where to initialize class and code to input and call?

### ISSUE THREAD

**Issue by veronicaginger** [pixelead0/tmdb_v3-PHP-API-#47]
I really frustrated in how to use the api wraper on Datalife engine. Any documentation or tutorial how to initialize it?

I already try to initialize the class in engine"/inc/addnews.php" ( initialize the class like this...

include ENGINE_DIR . '/engine/modules/tmdb-api.php'
// if you have a $conf array - (See LIB_ROOT/configuration/default.php as an example)
    $tmdb = new TMDB($conf);
And put the tmdb-api.php and all folders in "engine/modules"

But still can't and don't know how to make it works.

Hope someone will help :(

**Comment by bogdanfinn** [comment]
Hey, i don't know the Datalife Engine CMS System, so i don't know how to add PHP Code to this CMS System.

Do you receive any error messages? Are your code gets executed, when you visit the page where you implemented the API-Wrapper?

**Comment by veronicaginger** [comment]
i can't executed my code and i don't know where the problem is.
first i initialize the class in "public/engine/modules/addnews.php"

> ![screenshot_29](https://user-images.githubusercontent.com/31661940/30088310-cd2667c2-92cf-11e7-891e-44fe8aff402f.png)
then i upload "tmdb-php.api" and all folder(example, controller, and configuration) in "public/engine/modules/"

and then start edit "public/engine/inc/addnews.php" but i don't know how to make the input code and call code.
this the code format looks like 
![screenshot_30](https://user-images.githubusercontent.com/31661940/30088430-792de3e2-92d0-11e7-8d33-f9aabf6ce07b.png)
and this the default "post" looks like
![screenshot_31](https://user-images.githubusercontent.com/31661940/30088444-92ce87f2-92d0-11e7-80b7-04ab287b5d1b.png)

**Comment by bogdanfinn** [comment]
Looks like you inserted the code into a module or plugin of your CMS system which renders a different topic an never calls the tmdb-api-wrapper functionality.

First of all, we currently don't know what is your goal. The addNews plugin/module seems to be able to create or update news for you CMS system. What should the tmdb-api-wrapper should do here?

Maybe you should look for a tutorial or something link that in the Datalife Engine CMS Community which could teach you how to develop a plugin / module for your CMS System correctly?
I think this Repository and the maintainers have nothing to do with the Datalife Engine CMS System.

**Comment by veronicaginger** [comment]
i want to keep the form like this.
![screenshot_33](https://user-images.githubusercontent.com/31661940/30114318-b5f59880-9341-11e7-98d1-355f38715e8d.png)

and use this Repository  to fetch the TMDB data. is it possible?

**Comment by webstractions** [comment]
You may also want to look at a similar project for a WordPress plugin. Charlie Merland's WPMovieLibrary handles importing TMDB data into the form via AJAX. His repository is on [Github ](https://github.com/wpmovielibrary/wpmovielibrary/).

One caveat, he does not use the entire library from this repository. He opted to pull just the Movie API and a few supporting classes to get the job done. He had no need for library and wanted to keep the package size down. With that said, the mechanics are all there for you to adapt for your needs.
