### ISSUE TITLE
how to get crew and cast picture in infomovie.php

### ISSUE THREAD

**Issue by asifagaria** [pixelead0/tmdb_v3-PHP-API-#50]
Best API 
Hello Sir please need sum help to get picture for persons 
how to get crew and cast picture in infomovie.php

**Comment by bogdanfinn** [comment]
After https://github.com/pixelead0/tmdb_v3-PHP-API-/pull/49 is accepted you can get the crew and cast picture the way it is described in the infoPerson.php Exmaple file.

By now you can access the crew and cast data from a movie with my comment in:
https://github.com/pixelead0/tmdb_v3-PHP-API-/issues/48

When you iterating over the crew or the cast data you can access the picture by accessing the correct array key. For example:
`
$castArray = $movie->get('credits')['cast'];
 foreach($castArray as $castData){
$picturePath = $castData['profile_path'];
}
`

**Comment by asifagaria** [comment]
Thanks For replay
create a example  file please

**Comment by asifagaria** [comment]
Thanks 
I Do it 
but u make the all fix in example files for new users

**Comment by bogdanfinn** [comment]
Sorry i do not understand what you want :-(

**Comment by asifagaria** [comment]
$movie->get('credits')['cast']
$movie->get('credits')['crew']

$castArray = $movie->get('credits')['cast'];

foreach($castArray as $castData){
$picturePath = $castData['profile_path'];
}

the all classes files

**Comment by bogdanfinn** [comment]
I think you should wait for the Pull Request. Then it would be all clear.

This code sample i described is only a current workaround for accessing the data you want. After the PR it will be more easy to access the data.

**Comment by bogdanfinn** [comment]
@pixelead0 Issue could be closed, because of the mentioned PR
