### ISSUE TITLE
examples not working api problem

### ISSUE THREAD

**Issue by asifagaria** [pixelead0/tmdb_v3-PHP-API-#52]
solve it 
examples not working API problem

**Comment by pixelead0** [comment]
what's the error?

**Comment by asifagaria** [comment]
this api script inside examples folder the are not working default movies people search tvshows

**Comment by bogdanfinn** [comment]
Could you please provide a detailed error message or a screenshot of the error you receive when running the example script?

**Comment by bogdanfinn** [comment]
Please check if you set you api key for the tmdb api correctly in this file:
https://github.com/pixelead0/tmdb_v3-PHP-API-/blob/master/configuration/default.php

In line 8 enter you api key:
`$cnf['apikey'] = '';`

Without you personal api key the examples not working.

To register a new api key follow the steps described on this page:
https://developers.themoviedb.org/3/getting-started/introduction

**Comment by asifagaria** [comment]
thanks solve this

**Comment by bogdanfinn** [comment]
@pixelead0 Issue can be closed.

**Comment by P-L0** [comment]
How you solve this, I put key in examples/index.php and configuration/default.php but still dont work. I have error message :

unable to find example ()
