### ISSUE TITLE
How to get Movie/TV/Person search page ?

### ISSUE THREAD

**Issue by omar-elhamedy** [pixelead0/tmdb_v3-PHP-API-#58]
How to get the pages for search so I can connect it to my URL&page=(the number of the search page) ?
I tried to edit this part but I got an error and the same results when I passed the Page number? could you please help me with this ?

   ```
public function searchMovie($movieTitle,$page){

		$movies = array();

		$result = $this->_call('search/movie', '&query='. urlencode($movieTitle), '&page=' . $page);

		foreach($result['results'] as $data){
			$movies[] = new Movie($data);
		}

		return $movies;
	}
```

**The Error**

`Warning: Invalid argument supplied for foreach() in ...\controller\classes\config\Configuration.php on line 48`

Thanks

**Comment by iBringit** [comment]
you need to supply an array for foreach statement, instead you are providing a key value..

try

foreach ($result as $data)

// then fetch the results here 

remember $result returns an array you can fetch within the foreach statement as $ data

**Comment by omar-mohamed23** [comment]
Hi @iBringit  Thanks for your reply,
Please take a look at this code

```
// This is the code to get the page numper from the URL
if(isset($_GET['page'])){
    $page = $_GET['page'];
} else {
    $page = 1;
}

if($page == '' || $page == 1){
    $page1 = 0;
}else{
    $page1 = ($page*10)-10;

}

//This is my code for the search

foreach($multiSearchResults as $mediaType => $searchResults){
        foreach($searchResults as $searchResult) {
            if($searchResult->getMediaType() === 'movie') {
               echo" <div class='gridViewItem'>
                        <a href='/movies/movie?id=". $searchResult->getID() ."'><img class='backup_picture' id='poster' src='http://image.tmdb.org/t/p/original". $searchResult->getPoster() ."'></a>
                        <a href='/movies/movie?id=".$searchResult->getID()."'><div class='gridViewInfo'>"
                                . $searchResult->getTitle() .
                               "</div></a>


                        </div>";
            }}};
```

This code only show me the search result for the first page only from the API and I want to make a pagination on my website with each page show the results associated with the page number .
