### ISSUE TITLE
No ../tmdb-api.php file included, on this code

### ISSUE THREAD

**Issue by armansr** [pixelead0/tmdb_v3-PHP-API-#60]
include("../tmdb-api.php");

update this file where i get this file

**Comment by bogdanfinn** [comment]
Sorry, looks like the Filename was changes to TMDB.php and the examples are not updated.
See this Commit:
https://github.com/pixelead0/tmdb_v3-PHP-API-/commit/8559c67ca203b5b4632d49dd3b541c4eb6c1712d

You can modify the line:
```
include("../tmdb-api.php");
```
To
```
include("../TMDB.php");
```

Or rename the `TMDB.php` File in the root directory of this repository.
