### ISSUE TITLE
Empty youtube video problem

### ISSUE THREAD

**Issue by Hellsangels** [pixelead0/tmdb_v3-PHP-API-#63]
Hello

I have a problem with the youtube video displays. When the video exists in a film no worries everything works fine. The problem comes when there is no id of the youtube video I have this error 
`Notice: Undefined offset: 0 in C:\wamp64\www\pacaprez\engine\inc\class\api\tmdb\controller\classes\data\Movie.php on line 184`

Here is the code in question for the error
`	/** 
	 * 	Get the Movie's trailer
	 *
	 * 	@return string
	 */
	public function getTrailer() {
		$trailers = $this->getTrailers();
		return $trailers['youtube'][0]['source'];
	}`

So I would like to know how to not display when it is empty. Here is the code I use when there is a video
`echo '<br /><br /><b>Bande Annonce</b><br />
			<iframe width="560" height="315" src="https://www.youtube.com/embed/'. $movie->getTrailer() .'" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
			</iframe><br />';`

Thanks for your help and for your script

**Comment by bogdanfinn** [comment]
@Hellsangels i fixed the undefined offset issue on my fork `bogdanfinn/tmdb_v3-PHP-API-`
Nevertheless you have to check if the trailer is empty or not.

I added an example how to check for empty trailer in the infoMovie.php  ;-) Check the commit out

**Comment by Hellsangels** [comment]
I looked at the infomovie.php file and I didn't see any verification. Because the film I'm showing has no video, it's empty. So I thought of an if but it doesn't work

**Comment by Hellsangels** [comment]
Ok I found my answer here https://github.com/alvaro-octal/TMDB-PHP-API/commit/e945a75adc594c23f70504d2eda27f347f8fb78e I think you could update the file

**Comment by bogdanfinn** [comment]
@pixelead0 issue can be closed

**Comment by pixelead0** [comment]
Thanks @bogdanfinn
